import type { NextPage } from 'next';
import Head from 'next/head';

import Sidebar from '../components/Sidebar';

const Home: NextPage = () => {
  return (
    <div className="bg-black h-screen overflow-hidden">
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Sidebar />
      </main>

      <div></div>
    </div>
  );
};

export default Home;
